### ISSUE TITLE
Codowik incompatible with DokuWiki release 2020-07-29 "Hogfather"

### ISSUE THREAD

**Issue by anselmic** [evnix/codowik#16]
After upgrading to Hogfather, the sidebar stopped working so I had to revert to the previous DokuWiki release.

**Comment by csalgau** [comment]
Recently decided to upgrade an instance and hit this issue.
The problem is caused by having config:defer_js turned on in Hogfather, which makes jQuery load later that the template code.
Updating the code to use the dokuwiki include syntax causes issues with config:compress for js/layout.js.
Proposed fix minimally address these issues.
